# Site settings
title: My Blog          # 博客标题
email: myemail@example.com # 博客联系邮箱
description: >-         # 博客描述
  This is my awesome blog.
baseurl: ""             # 基础 URL，例如 /blog，如果站点在子目录中
url: "https://jimmy.github.io" # 你的博客 URL

# Build settings
markdown: kramdown      # 使用的 Markdown 引擎
theme: minima           # 使用的 Jekyll 主题
plugins:
  - jekyll-feed         # RSS 订阅插件
  - jekyll-theme-cayman
  - jekyll-seo-tag

# Social media settings
twitter_username: your_twitter_handle
github_username:  your_github_handle

# Other settings
paginate: 5             # 分页，每页文章数
paginate_path: "/page:num/"